name: deploy-to-aws
run-name: Deploying {{ github.ref }}
on:
  push:
    # branches:
    #   - "main"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref:"main"
      - run: echo "checked out main!"

  build code:
    runs-on: ubuntu-latest
    - uses: actions/setup-node@v6
      with:
        node-version: 'latest'
    - run: npm install && npm run build
